import type {
  EncounterActDefinition,
  EncounterCardDefinition,
  EncounterDeckDefinition,
} from "../domain/encounterDirector";
import { ENCOUNTER_DIRECTIONS } from "../domain/encounterDirector";

export const FINAL_EXPEDITION_ENCOUNTER_DECK_ID = "final-expedition-v1";

export const FINAL_EXPEDITION_ACTS: EncounterActDefinition[] = [
  { id: "perimeter-watch", titleKey: "act.perimeter-watch.title", startsAt: 0 },
  { id: "first-assault", titleKey: "act.first-assault.title", startsAt: 75 },
  { id: "counterattack", titleKey: "act.counterattack.title", startsAt: 180 },
  { id: "breakthrough", titleKey: "act.breakthrough.title", startsAt: 300 },
  { id: "command-ship", titleKey: "act.command-ship.title", startsAt: 390 },
];

export const FINAL_EXPEDITION_ENCOUNTER_CARDS: EncounterCardDefinition[] = [
  {
    id: "vanguard-arc",
    titleKey: "encounter.vanguard-arc.title",
    tags: ["vanguard"],
    actIds: ["perimeter-watch"],
    blocksActClock: false,
    deployment: null,
    timing: { telegraphSeconds: 1.4, activeSeconds: 14, recoverySeconds: 4 },
    spawn: {
      intervalMultiplier: 0.92,
      budget: 2,
      enemyWeights: { chaser: 1 },
      geometryId: "arc",
    },
    minimumThreatTier: 0,
    cooldownSeconds: 24,
    weight: 2,
    completionCondition: { type: "duration" },
    failureSignalIds: [],
    interruptSignalIds: [],
  },
  {
    id: "crossfire-pincer",
    titleKey: "encounter.crossfire-pincer.title",
    tags: ["crossfire"],
    actIds: ["first-assault"],
    blocksActClock: false,
    deployment: null,
    timing: { telegraphSeconds: 1.6, activeSeconds: 17, recoverySeconds: 4 },
    spawn: {
      intervalMultiplier: 0.88,
      budget: 3,
      enemyWeights: { chaser: 1, brute: 0.7 },
      geometryId: "pincer",
    },
    minimumThreatTier: 0,
    cooldownSeconds: 30,
    weight: 2,
    completionCondition: { type: "duration" },
    failureSignalIds: [],
    interruptSignalIds: [],
  },
  {
    id: "heavy-escort",
    titleKey: "encounter.heavy-escort.title",
    tags: ["heavy"],
    actIds: ["first-assault"],
    blocksActClock: false,
    deployment: null,
    timing: { telegraphSeconds: 1.8, activeSeconds: 18, recoverySeconds: 4.5 },
    spawn: {
      intervalMultiplier: 0.9,
      budget: 4,
      enemyWeights: { chaser: 0.6, brute: 1.5 },
      geometryId: "escort",
    },
    minimumThreatTier: 0,
    cooldownSeconds: 36,
    weight: 2,
    completionCondition: { type: "duration" },
    failureSignalIds: [],
    interruptSignalIds: [],
  },
  {
    id: "commander-counterattack",
    titleKey: "encounter.commander-counterattack.title",
    tags: ["commander"],
    actIds: ["counterattack"],
    blocksActClock: true,
    deployment: {
      retryIntervalSeconds: 2,
      timeoutSeconds: 10,
    },
    timing: { telegraphSeconds: 2.2, activeSeconds: 120, recoverySeconds: 4.5 },
    spawn: {
      intervalMultiplier: 0.92,
      budget: 4,
      enemyWeights: { chaser: 1.2, fast: 0.45 },
      geometryId: "escort",
    },
    minimumThreatTier: 0,
    cooldownSeconds: 600,
    weight: 1,
    completionCondition: { type: "signal", signalId: "commander-defeated" },
    failureSignalIds: [],
    interruptSignalIds: [],
  },
  {
    id: "charger-breakthrough",
    titleKey: "encounter.charger-breakthrough.title",
    tags: ["charger"],
    actIds: ["breakthrough"],
    blocksActClock: false,
    deployment: null,
    timing: { telegraphSeconds: 2, activeSeconds: 19, recoverySeconds: 4.5 },
    spawn: {
      intervalMultiplier: 0.84,
      budget: 4,
      enemyWeights: { chaser: 0.7, fast: 1.6, ranged: 0.45 },
      geometryId: "arc",
    },
    minimumThreatTier: 0,
    cooldownSeconds: 150,
    weight: 2,
    completionCondition: { type: "duration" },
    failureSignalIds: [],
    interruptSignalIds: [],
  },
  {
    id: "command-ship-showdown",
    titleKey: "encounter.command-ship-showdown.title",
    tags: ["boss"],
    actIds: ["command-ship"],
    blocksActClock: false,
    deployment: null,
    timing: { telegraphSeconds: 2.4, activeSeconds: 240, recoverySeconds: 2.5 },
    spawn: {
      intervalMultiplier: 1,
      budget: 1,
      enemyWeights: { brute: 1 },
      geometryId: "escort",
    },
    minimumThreatTier: 0,
    cooldownSeconds: 600,
    weight: 1,
    completionCondition: { type: "signal", signalId: "boss-defeated" },
    failureSignalIds: [],
    interruptSignalIds: [],
  },
];

export const FINAL_EXPEDITION_ENCOUNTER_DECK: EncounterDeckDefinition = {
  id: FINAL_EXPEDITION_ENCOUNTER_DECK_ID,
  cardIds: FINAL_EXPEDITION_ENCOUNTER_CARDS.map((card) => card.id),
  directionIds: [...ENCOUNTER_DIRECTIONS],
  initialDelay: { minSeconds: 16, maxSeconds: 22 },
  interval: { minSeconds: 24, maxSeconds: 32 },
  retryDelaySeconds: 2,
};
