import type { UpgradeDefinition, UpgradeId } from "../domain/types";

export const UPGRADE_DEFINITIONS: Record<UpgradeId, UpgradeDefinition> = {
  rapidFire: {
    id: "rapidFire",
    title: "Rapid Fire",
    description: "Shoot 15% faster",
    category: "weapon",
    maxRank: 5,
    weight: 1,
    effect: { type: "fireIntervalMultiplier", multiplier: 0.85 },
  },
  swiftStep: {
    id: "swiftStep",
    title: "Swift Step",
    description: "Move 12% faster",
    category: "mobility",
    maxRank: 5,
    weight: 1,
    effect: { type: "moveSpeedMultiplier", multiplier: 1.12 },
  },
  vitalCore: {
    id: "vitalCore",
    title: "Vital Core",
    description: "Gain 20 max HP",
    category: "survival",
    maxRank: 4,
    weight: 0.8,
    effect: { type: "maxHp", amount: 20 },
  },
  overdriveRounds: {
    id: "overdriveRounds",
    title: "Overdrive Rounds",
    description: "Projectiles fly faster; Pulse gains 22% per rank",
    category: "weapon",
    maxRank: 5,
    weight: 0.9,
    effect: {
      type: "projectileSpeedMultiplier",
      multiplier: 1.15,
      weaponMultipliers: { pulse: 1.22 },
    },
  },
  splitShot: {
    id: "splitShot",
    title: "Split Shot",
    description: "Add one projectile",
    category: "weapon",
    maxRank: 2,
    weight: 0.7,
    effect: { type: "projectileCount", amount: 1 },
    requirements: {
      weaponIds: ["spread"],
    },
  },
  pulseFocus: {
    id: "pulseFocus",
    title: "Pulse Focus",
    description: "Direct hits build damage against the same target",
    category: "weapon",
    maxRank: 2,
    weight: 0.7,
    effect: {
      type: "pulseFocus",
      bonusPerStack: 0.15,
      stacksPerRank: 2,
      duration: 0.9,
    },
    requirements: {
      weaponIds: ["pulse"],
      featureFlag: "pulseFocus",
    },
  },
  piercingRounds: {
    id: "piercingRounds",
    title: "Piercing Rounds",
    description: "Increase hit capacity by one",
    category: "support",
    maxRank: 3,
    weight: 0.8,
    effect: { type: "hitCapacity", amount: 1 },
  },
  pulseRicochet: {
    id: "pulseRicochet",
    title: "Pulse Ricochet",
    description: "Pulse shots ricochet once from obstacles or the arena boundary",
    category: "capstone",
    maxRank: 1,
    weight: 1,
    effect: { type: "ricochet", amount: 1 },
    requirements: {
      weaponIds: ["pulse"],
      minimumCategoryRanks: { weapon: 7 },
      featureFlag: "pulseRicochet",
    },
  },
  spreadSweep: {
    id: "spreadSweep",
    title: "Spread Sweep",
    description: "Hit three targets in one volley to accelerate the next volley",
    category: "capstone",
    maxRank: 1,
    weight: 1,
    effect: {
      type: "spreadSweep",
      distinctTargets: 3,
      nextIntervalMultiplier: 0.7,
    },
    requirements: {
      weaponIds: ["spread"],
      minimumCategoryRanks: { weapon: 7 },
      featureFlag: "spreadSweep",
    },
  },
};
