export const ARENA_DYNAMIC_WORLD_DEPTH = 0;

export const TUTORIAL_CHECKLIST_GRAPHICS_DEPTH = -2;
export const TUTORIAL_CHECKLIST_TEXT_DEPTH = -1;

export const TUTORIAL_OVERLAY_GRAPHICS_DEPTH = 12;
export const TUTORIAL_OVERLAY_TEXT_DEPTH = 13;
