export const ARENA_DYNAMIC_WORLD_DEPTH = 0;
export const ARENA_STATIC_WORLD_DEPTH = -5;
export const ARENA_PROJECTILE_DEPTH = 0.5;
export const ARENA_ENTITY_DEPTH = 1;
export const ARENA_SCREEN_GRAPHICS_DEPTH = 9;
export const ARENA_SCREEN_ENTITY_PREVIEW_DEPTH = 20.5;
export const ARENA_CURSOR_DEPTH = 40;

export const PRACTICE_GUIDE_TEXT_DEPTH = -10;

export const TUTORIAL_CHECKLIST_GRAPHICS_DEPTH = -2;
export const TUTORIAL_CHECKLIST_TEXT_DEPTH = -1;

export const TUTORIAL_OVERLAY_GRAPHICS_DEPTH = 12;
export const TUTORIAL_OVERLAY_TEXT_DEPTH = 13;

export const HELP_OVERLAY_GRAPHICS_DEPTH = 30;
export const HELP_OVERLAY_ENTITY_DEPTH = 30.5;
export const HELP_OVERLAY_TEXT_DEPTH = 31;
