import {
  ENDLESS_RULESET_VERSION,
  EX_PROTOCOL_ENDLESS_RULESET_VERSION,
  RULESET_VERSION,
  UPGRADE_CATEGORY_FLOOR_ENDLESS_RULESET_VERSION,
  resolveBuildReleaseIdentity,
} from "../../src/config/version";

export const EX_PROTOCOL_CANDIDATE_ENABLED =
  process.env.VITE_ARENA_EX_PROTOCOL_CANDIDATE === "1";
export const UPGRADE_CATEGORY_FLOOR_CANDIDATE_ENABLED =
  process.env.VITE_ARENA_UPGRADE_CATEGORY_FLOOR_CANDIDATE === "1";
export const EX_PROTOCOLS_ENABLED =
  EX_PROTOCOL_CANDIDATE_ENABLED || UPGRADE_CATEGORY_FLOOR_CANDIDATE_ENABLED;
export const RUN_RECORD_STORAGE_KEY = EX_PROTOCOLS_ENABLED
  ? "arena-core.run-records.v3"
  : "arena-core.run-records.v2";
export const RELEASE_IDENTITY = resolveBuildReleaseIdentity(
  EX_PROTOCOL_CANDIDATE_ENABLED,
  UPGRADE_CATEGORY_FLOOR_CANDIDATE_ENABLED,
);
export const ACTIVE_ENDLESS_RULESET_VERSION =
  UPGRADE_CATEGORY_FLOOR_CANDIDATE_ENABLED
    ? UPGRADE_CATEGORY_FLOOR_ENDLESS_RULESET_VERSION
    : EX_PROTOCOL_CANDIDATE_ENABLED
      ? EX_PROTOCOL_ENDLESS_RULESET_VERSION
      : ENDLESS_RULESET_VERSION;
export const ACTIVE_CONFIG_VERSION = RULESET_VERSION;
export const ACTIVE_ENDLESS_RULESET_PROFILE_ID =
  UPGRADE_CATEGORY_FLOOR_CANDIDATE_ENABLED
    ? "candidate-upgrade-floor-endless-v08"
    : EX_PROTOCOL_CANDIDATE_ENABLED
      ? "candidate-ex-endless-c2"
      : "legacy-endless-v068";
export const ACTIVE_RANK_EXCLUSION_REASONS = EX_PROTOCOLS_ENABLED
  ? ["automatedTest", "nonStandardRuleset"]
  : ["automatedTest"];
