import { UPGRADE_IDS } from "../domain/types";
import { createEmptyExProtocolRunStats } from "../domain/exProtocolTelemetry";
import type {
  SimulationConfig,
  WeaponComparisonRunStats,
  WeaponRunStats,
  WorldState,
} from "../domain/types";
import { createEmptyExtraUpgradeRanks } from "./extraProgression";

export function createWorld(config: SimulationConfig): WorldState {
  const upgradeRanks = Object.fromEntries(
    UPGRADE_IDS.map((id) => [id, 0]),
  ) as WorldState["progression"]["upgradeRanks"];

  return {
    state: {
      status: "playing",
      elapsed: 0,
      score: 0,
      hp: config.player.maxHp,
      spawnTimer: 0.25,
      shotTimer: 0,
      damageCooldown: 0,
      lastAim: { x: 1, y: 0 },
      weaponType: config.defaultWeapon,
    },
    progression: {
      level: 1,
      extraLevel: 0,
      extraCycle: 0,
      xp: 0,
      xpToNext: config.leveling.baseXp,
      buildCompletedAt: null,
      pendingUpgradeChoices: [],
      upgradeRanks,
      extraUpgradeRanks: createEmptyExtraUpgradeRanks(),
      extraCycleRemaining: [],
    },
    runtime: {
      playerSpeedMultiplier: 1,
      fireIntervalMultiplier: 1,
      projectileSpeedMultiplier: 1,
      projectileDamageMultiplier: 1,
      maxHpBonus: 0,
      projectileCountBonus: 0,
      hitCapacityBonus: 0,
      ricochetBonus: 0,
      pulseFocusBonusPerStack: 0,
      pulseLineBonusPerStack: 0,
      pulseFocusMaxStacks: 0,
      pulseFocusDuration: 0,
      spreadSweepDistinctTargets: 0,
      spreadSweepNextIntervalMultiplier: 1,
      healDropMissCount: 0,
      healDropRollIndex: 0,
    },
    stats: {
      shotsFired: 0,
      enemiesKilled: 0,
      hitsTaken: 0,
      damageTaken: 0,
      damageTakenBySource: { contact: 0, projectile: 0, collapse: 0 },
      lastDamageSource: null,
      xpCollected: 0,
      pickupsCollected: 0,
      hpRecovered: 0,
      healPickupsCollected: 0,
      effectiveHealPickupsCollected: 0,
      upgradesChosen: 0,
      extraUpgradesChosen: 0,
      movementDistance: 0,
      navigationMetrics: {
        directFrames: 0,
        pathFrames: 0,
        fallbackFrames: 0,
        fieldBuilds: 0,
      },
      progressionMetrics: {
        firstOfferAt: null,
        firstSelectionAt: null,
        lastSelectionAt: null,
        buildCompletedAt: null,
        longestMeaningfulChoiceGap: 0,
        offers: [],
        selections: [],
        extraStartedAt: null,
        extraOffers: 0,
        extraSelections: [],
      },
      capstoneMetrics: {
        upgradeId: null,
        acquiredAt: null,
        activations: 0,
        followUpHits: 0,
        followUpUniqueEnemiesHit: 0,
        maxFollowUpUniqueEnemiesPerVolley: 0,
        obstacleRicochets: 0,
        boundaryRicochets: 0,
        boundaryRicochetsBySide: { left: 0, right: 0, top: 0, bottom: 0 },
        obstacleFollowUpHits: 0,
        obstacleFollowUpKills: 0,
        boundaryFollowUpHits: 0,
        boundaryFollowUpKills: 0,
        boundaryFollowUpHitsBySide: { left: 0, right: 0, top: 0, bottom: 0 },
        spreadSweepTriggers: 0,
        spreadSweepConsumes: 0,
      },
      weaponIdentityMetrics: {
        pulseFocus: {
          enhancedHits: 0,
          bonusDamage: 0,
          targetEnhancedHits: 0,
          lineEnhancedHits: 0,
          targetBonusDamage: 0,
          lineBonusDamage: 0,
          maxStacks: 0,
          killsByEnemyType: { chaser: 0, brute: 0, fast: 0, ranged: 0 },
        },
        spreadSweep: {
          triggers: 0,
          consumes: 0,
          maxDistinctTargets: 0,
        },
      },
      encounterMetrics: {
        scheduledAt: null,
        warningStartedAt: null,
        activeStartedAt: null,
        recoveryStartedAt: null,
        completedAt: null,
        rangedEnemiesSpawned: 0,
        damageTakenDuringActive: 0,
        killsDuringActiveByEnemyType: { chaser: 0, brute: 0, fast: 0, ranged: 0 },
        movement: {
          baseline: { distance: 0, vector: { x: 0, y: 0 } },
          warning: { distance: 0, vector: { x: 0, y: 0 } },
          active: { distance: 0, vector: { x: 0, y: 0 } },
          recovery: { distance: 0, vector: { x: 0, y: 0 } },
        },
        contractOfferedAt: null,
        contractSelectedAt: null,
        contractChoice: null,
        eventCounts: { rangedSurge: 0, swarmRush: 0, bruteSiege: 0 },
        eventsCompleted: 0,
        collapseStartedAt: null,
        peakCollapseStage: 0,
        collapseDamageTaken: 0,
        commander: {
          spawned: 0,
          killed: 0,
          telegraphs: 0,
          traitActivations: 0,
          reinforcementsSpawned: 0,
          pressureReleases: 0,
          supportUnitsReleased: 0,
          lifetimeTotal: 0,
          killsByWeapon: { pulse: 0, spread: 0, pierce: 0 },
        },
        charger: {
          spawned: 0,
          telegraphs: 0,
          charges: 0,
          killedBeforeTelegraph: 0,
          playerHits: 0,
          avoided: 0,
          obstacleInterruptions: 0,
          boundaryInterruptions: 0,
          recoveries: 0,
          killed: 0,
          killsByWeapon: { pulse: 0, spread: 0, pierce: 0 },
        },
      },
      weaponMetrics: {
        pulse: createWeaponRunStats(),
        spread: createWeaponRunStats(),
        pierce: createWeaponRunStats(),
      },
      weaponComparisonMetrics: {
        pulse: createWeaponComparisonRunStats(),
        spread: createWeaponComparisonRunStats(),
        pierce: createWeaponComparisonRunStats(),
      },
      exProtocolMetrics: createEmptyExProtocolRunStats(),
    },
    analytics: {
      activeVolleys: {},
    },
    weaponIdentity: {
      spreadSweepCharge: false,
    },
    eliteState: {
      commanderIds: [],
    },
    enemyActionState: {
      chargerIds: [],
    },
    encounter: {
      director: {
        phase: "pending",
        currentId: null,
        scheduledAt: null,
        warningStartedAt: null,
        activeStartedAt: null,
        recoveryStartedAt: null,
        completedCount: 0,
        bag: [],
        history: [],
      },
      contract: {
        status: "pending",
        choice: null,
        offeredAt: null,
        selectedAt: null,
        enemySpeedMultiplier: 1,
        scoreMultiplier: 1,
      },
      collapse: {
        stage: 0,
        inset: 0,
        damageTimer: 0,
      },
    },
    player: {
      id: "player",
      position: { x: config.player.x, y: config.player.y },
      radius: config.player.radius,
    },
    bullets: [],
    enemies: [],
    enemyProjectiles: [],
    pickups: [],
    obstacles: config.obstacles.map((obstacle) => ({ ...obstacle })),
    nextBulletId: 1,
    nextVolleyId: 1,
    nextEnemyId: 1,
    nextEnemyProjectileId: 1,
    nextPickupId: 1,
  };
}

function createWeaponRunStats(): WeaponRunStats {
  return {
    shotsFired: 0,
    projectilesFired: 0,
    hits: 0,
    kills: 0,
  };
}

function createWeaponComparisonRunStats(): WeaponComparisonRunStats {
  return {
    hitVolleys: 0,
    uniqueEnemiesHit: 0,
    maxUniqueEnemiesHitPerVolley: 0,
    hitsByEnemyType: { chaser: 0, brute: 0, fast: 0, ranged: 0 },
    killsByEnemyType: { chaser: 0, brute: 0, fast: 0, ranged: 0 },
  };
}
