import type { ConceptDefinition, PrototypeData } from "./types";

export const CONCEPTS: ConceptDefinition[] = [
  {
    id: "tactical",
    index: "A",
    label: "戦術管制",
    shortLabel: "管制",
    systemLabel: "TACTICAL CONTROL",
    stageVerb: "作戦を展開",
    primaryAction: "出撃経路を選択",
  },
  {
    id: "recovery",
    index: "B",
    label: "回収航路",
    shortLabel: "航路",
    systemLabel: "RECOVERY LINE",
    stageVerb: "航路を接続",
    primaryAction: "回収線を維持",
  },
  {
    id: "arcade",
    index: "C",
    label: "精密アーケード",
    shortLabel: "精密",
    systemLabel: "PRECISION SCORE",
    stageVerb: "チャレンジ開始",
    primaryAction: "限界記録へ挑む",
  },
];

export const PROTOTYPE_DATA: PrototypeData = {
  productName: "ARENA CORE",
  tagline: "包囲を読み、射線を通し、生存限界を更新する。",
  runLabel: "FINAL EXPEDITION / STAGE 10",
  stages: [
    {
      id: "border-watch",
      number: "01",
      title: "境界哨戒",
      subtitle: "四方からの侵入と回収を学ぶ",
      difficulty: "導入",
      duration: "03:30",
      enemyTypes: ["追跡"],
      objective: "敵の侵入方向を読み、指定時間を生存する",
      status: "cleared",
    },
    {
      id: "broken-route",
      number: "05",
      title: "回収線崩壊",
      subtitle: "高速隊と射撃隊の混成包囲",
      difficulty: "標準",
      duration: "06:00",
      enemyTypes: ["追跡", "重装", "高速", "射撃"],
      objective: "危険イベントを突破し、回収経路を維持する",
      status: "available",
    },
    {
      id: "final-expedition",
      number: "10",
      title: "敵指揮艦決戦",
      subtitle: "5 Actを突破する最終遠征",
      difficulty: "最終",
      duration: "09:00+",
      enemyTypes: ["全兵科", "指揮個体", "突撃", "指揮艦"],
      objective: "増援を処理しながら敵指揮艦を撃破する",
      status: "available",
    },
  ],
  upgrades: [
    {
      id: "pulse-focus",
      category: "武器",
      title: "集束共鳴",
      description: "同じ標的と貫通線への連続命中で威力を上げる",
      rank: "2 / 2",
      metric: "集束上限 2 -> 4",
      accent: "pulse",
    },
    {
      id: "swift-step",
      category: "機動",
      title: "軽快な足取り",
      description: "回避と回収へ使う移動速度を引き上げる",
      rank: "3 / 5",
      metric: "移動速度 304 -> 340",
      accent: "mobility",
    },
    {
      id: "vital-core",
      category: "生存",
      title: "生命コア",
      description: "最大HPを増やし、危険イベントの猶予を作る",
      rank: "1 / 4",
      metric: "最大HP 120 -> 140",
      accent: "survival",
    },
  ],
  combat: {
    hp: 74,
    maxHp: 140,
    xp: 92,
    xpToNext: 120,
    level: 18,
    elapsed: "07:01",
    score: 15800,
    threat: 5,
    enemies: 70,
    weapon: "パルス",
    bossHp: 1530,
    bossMaxHp: 3400,
    bossPhase: 2,
    event: "照準斉射",
  },
  result: {
    score: 141292,
    elapsed: "07:01",
    clearBonus: 15000,
    timeBonus: 107992,
    bossTime: "00:43",
    level: 31,
    kills: 1842,
    damageTaken: 716,
    rank: "S",
    build: ["集束共鳴 2", "加速弾 5", "貫通弾 3", "反響回路"],
  },
};
