export type SecondaryMenu =
  | "history"
  | "ranking"
  | "settings"
  | "practice"
  | "story"
  | "practiceSettings"
  | "help";

export type HistoryWeaponFilter = "all" | "pulse" | "spread";
export type HelpPage = "controls" | "enemies" | "field";

export type MenuAction =
  | "story"
  | "start"
  | "startExpedition"
  | "startTraining"
  | "practice"
  | "practiceSettings"
  | "practiceInvincible"
  | "practiceInvinciblePrevious"
  | "practiceInvincibleNext"
  | "practiceIntensity"
  | "practiceIntensityPrevious"
  | "practiceIntensityNext"
  | "practiceEnemyChaser"
  | "practiceEnemyBrute"
  | "practiceEnemyFast"
  | "practiceEnemyRanged"
  | "practiceStartPulse"
  | "practiceStartSpread"
  | "selectPulse"
  | "selectSpread"
  | "contractStandard"
  | "contractOverdrive"
  | "resume"
  | "restart"
  | "title"
  | "history"
  | "ranking"
  | "settings"
  | "help"
  | "helpControls"
  | "helpEnemies"
  | "helpField"
  | "betaInfo"
  | "back"
  | "historyPrevious"
  | "historyNext"
  | "historyFilterAll"
  | "historyFilterPulse"
  | "historyFilterSpread"
  | "rankingPrevious"
  | "rankingNext"
  | "clearHistory"
  | "clearRankings"
  | "resetSettings"
  | "resetProfile"
  | "settingsBgm"
  | "settingsSfx"
  | "settingsShake"
  | "settingsFlash"
  | "settingsAutoFire";
