export type SecondaryMenu = "history" | "ranking" | "settings";

export type HistoryWeaponFilter = "all" | "pulse" | "spread";

export type MenuAction =
  | "start"
  | "startExpedition"
  | "startTraining"
  | "selectPulse"
  | "selectSpread"
  | "contractStandard"
  | "contractOverdrive"
  | "resume"
  | "restart"
  | "title"
  | "history"
  | "ranking"
  | "settings"
  | "betaInfo"
  | "back"
  | "historyPrevious"
  | "historyNext"
  | "historyFilterAll"
  | "historyFilterPulse"
  | "historyFilterSpread"
  | "rankingPrevious"
  | "rankingNext"
  | "clearHistory"
  | "clearRankings"
  | "resetSettings"
  | "resetProfile"
  | "settingsBgm"
  | "settingsSfx"
  | "settingsShake"
  | "settingsFlash"
  | "settingsAutoFire";
